language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
    - node_modules
script:
    - yarn lint
    - npm install -g serverless
    - sls dynamodb install
    - sls offline start --exec "yarn functional-local"
    - sls deploy -s dev
    - yarn functional-dev
    - sls deploy -s prod

