language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - sh serverless.env.sh
jobs:
  include:
    - stage: remove
      script: ".ci/remove.sh"
      if: commit_message =~ /(redeploy)/
    - stage: deploy
      script: ".ci/deploy.sh"
    - stage: logging
      script: ".ci/logging.sh"
      if: commit_message =~ /(redeploy)/
