language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
    - node_modules
script:
    - yarn lint
    - npm install -g serverless
    - sls dynamodb install
    - sls offline start --exec "yarn functional-local"
    - sls deploy -s dev
    - yarn functional-remote-dev
    - sls deploy -s prod
    - yarn functional-remote-prod

