language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - sh serverless.env.sh
before_install:
  - chmod +x .ci/remove.sh
  - chmod +x .ci/deploy.sh
  - chmod +x .ci/logging.sh
  - npm install -g serverless
jobs:
  include:
    - stage: remove
      script: ".ci/remove.sh"
      if: commit_message =~ /(redeploy)/
    - stage: deploy
      script: ".ci/deploy.sh"
    - stage: logging
      script: ".ci/logging.sh"
      if: commit_message =~ /(recreatelogging)/
