service: fotopia-web-app

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-s3-sync
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-s3-local-sync
  - serverless-offline
  - serverless-stack-output
  - serverless-s3-remover

custom:
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  s3:
    host: 0.0.0.0
    port: 5000
    directory: /tmp/s3bucket
    cors: false
  s3Sync:
    - bucketName: ${self:provider.environment.S3_CLIENT_BUCKET}
      localDir: client
  output:
    file: client/output.json
  remover:
     buckets:
       - ${self:provider.environment.S3_CLIENT_BUCKET}
       - ${self:provider.environment.S3_BUCKET}

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  profile: default
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    S3_BUCKET: ${self:service}-${opt:stage, self:provider.stage}
    S3_CLIENT_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-client
    LAMBDA_GET: ${self:service}-${opt:stage, self:provider.stage}-get
    LAMBDA_GET_OFFLINE: get
    USER_POOL_NAME: ${self:service}-${opt:stage, self:provider.stage}-user-pool
    USER_POOL_APP_CLIENT: ${self:service}-${opt:stage, self:provider.stage}-user-pool-client
    IDENTITY_POOL: fotopia ${opt:stage, self:provider.stage} identity pool
    COGNITO_AUTHORIZED_ROLE_NAME: ${self:service}-${opt:stage, self:provider.stage}-auth-role-name
    COGNITO_AUTHORIZED_POLICY: ${self:service}-${opt:stage, self:provider.stage}-auth-policy
    COGNITO_AUTHORIZED_S3_POLICY: ${self:service}-${opt:stage, self:provider.stage}-auth-s3-policy
    COGNITO_AUTHORIZED_API_POLICY: ${self:service}-${opt:stage, self:provider.stage}-auth-api-policy
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource:
        - "*"
        - "arn:aws:lambda:*:*:*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:DescribeLogStreams
      Resource:
        - "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  create:
    handler: fotos/create.createItem
    events:
      - http:
          path: create
          method: post
          cors: true

  query:
    handler: fotos/query.queryItems
    events:
      - http:
          path: query
          method: post
          cors: true

  get:
    handler: fotos/get.getItem
    events:
      - http:
          path: foto/{userid}/{birthtime}
          method: get
          cors: true

  update:
    handler: fotos/update.updateItem
    events:
      - http:
          path: foto/{userid}/{birthtime}
          method: put
          cors: true

  delete:
    handler: fotos/delete.deleteItem
    events:
      - http:
          path: foto/{userid}/{birthtime}
          method: delete
          cors: true

resources:
  Resources:
    FotopiaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
          - AttributeName: birthtime
            AttributeType: N
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
          - AttributeName: birthtime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    FotopiaBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        AccessControl: PublicRead
    FotopiaClient:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:provider.environment.S3_CLIENT_BUCKET}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    FotopiaPublicPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: ${self:provider.environment.S3_BUCKET}
        PolicyDocument:
          Statement:
          - Principal: "*"
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:provider.environment.USER_POOL_NAME}
        AutoVerifiedAttributes:
          - email
        #EmailVerificationMessage: String
        #EmailVerificationSubject: String
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
    UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:provider.environment.USER_POOL_APP_CLIENT}
        RefreshTokenValidity: 30
        ExplicitAuthFlows: [ADMIN_NO_SRP_AUTH]
        GenerateSecret: false
        UserPoolId:
          Ref: UserPool
    IdentityPool:
      Type: "AWS::Cognito::IdentityPool"
      Properties:
        IdentityPoolName: ${self:provider.environment.IDENTITY_POOL}
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId:
              Ref: UserPoolClient
            ProviderName:
              Fn::GetAtt: [ UserPool, ProviderName ]
    CognitoAuthorizedRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ${self:provider.environment.COGNITO_AUTHORIZED_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: IdentityPool
        Policies:
          - PolicyName: ${self:provider.environment.COGNITO_AUTHORIZED_POLICY}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
          - PolicyName: ${self:provider.environment.COGNITO_AUTHORIZED_S3_POLICY}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:*"
                  Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*
          - PolicyName: ${self:provider.environment.COGNITO_AUTHORIZED_API_POLICY}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                  Resource: "arn:aws:execute-api:${self:provider.region}:*:*/*"
    IdentityPoolRoleMapping:
      Type: "AWS::Cognito::IdentityPoolRoleAttachment"
      Properties:
        IdentityPoolId:
          Ref: IdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [ CognitoAuthorizedRole, Arn ]
  Outputs:
    UserPoolId:
      Value:
        Ref: UserPool
      Export:
        Name: "UserPool::Id"
    UserPoolClientId:
      Value:
        Ref: UserPoolClient
      Export:
        Name: "UserPoolClient::Id"
    IdentityPoolId:
      Value:
        Ref: IdentityPool
      Export:
        Name: "IdentityPool::Id"
    CognitoAuthorizedRoleArn:
      Value:
        Fn::GetAtt: [ CognitoAuthorizedRole, Arn ]
      Export:
        Name: "CognitoAuthorizedRole::Arn"

package:
  exclude:
    - node_modules/**
    - '!node_modules/joi/**'
    - '!node_modules/uuid/**'
    - '!node_modules/babel-runtime/**'
